#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: f4a13a5
#
Name     : R-quadprog
Version  : 1.5.8
Release  : 69
URL      : https://cran.r-project.org/src/contrib/quadprog_1.5-8.tar.gz
Source0  : https://cran.r-project.org/src/contrib/quadprog_1.5-8.tar.gz
Summary  : Functions to Solve Quadratic Programming Problems
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-quadprog-lib = %{version}-%{release}
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
solving quadratic programming problems.

%package lib
Summary: lib components for the R-quadprog package.
Group: Libraries

%description lib
lib components for the R-quadprog package.


%prep
%setup -q -n quadprog
pushd ..
cp -a quadprog buildavx2
popd
pushd ..
cp -a quadprog buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1737154614

%install
export SOURCE_DATE_EPOCH=1737154614
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/quadprog/DESCRIPTION
/usr/lib64/R/library/quadprog/INDEX
/usr/lib64/R/library/quadprog/Meta/Rd.rds
/usr/lib64/R/library/quadprog/Meta/features.rds
/usr/lib64/R/library/quadprog/Meta/hsearch.rds
/usr/lib64/R/library/quadprog/Meta/links.rds
/usr/lib64/R/library/quadprog/Meta/nsInfo.rds
/usr/lib64/R/library/quadprog/Meta/package.rds
/usr/lib64/R/library/quadprog/NAMESPACE
/usr/lib64/R/library/quadprog/R/quadprog
/usr/lib64/R/library/quadprog/R/quadprog.rdb
/usr/lib64/R/library/quadprog/R/quadprog.rdx
/usr/lib64/R/library/quadprog/help/AnIndex
/usr/lib64/R/library/quadprog/help/aliases.rds
/usr/lib64/R/library/quadprog/help/paths.rds
/usr/lib64/R/library/quadprog/help/quadprog.rdb
/usr/lib64/R/library/quadprog/help/quadprog.rdx
/usr/lib64/R/library/quadprog/html/00Index.html
/usr/lib64/R/library/quadprog/html/R.css
/usr/lib64/R/library/quadprog/tests/Gwen.R
/usr/lib64/R/library/quadprog/tests/Gwen.Rout.save
/usr/lib64/R/library/quadprog/tests/TalbotKatz.R
/usr/lib64/R/library/quadprog/tests/TalbotKatz.Rout.save
/usr/lib64/R/library/quadprog/tests/bug.RData
/usr/lib64/R/library/quadprog/tests/test1.R
/usr/lib64/R/library/quadprog/tests/test1.Rout.save
/usr/lib64/R/library/quadprog/tests/test2.R
/usr/lib64/R/library/quadprog/tests/test2.Rout.save

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/quadprog/libs/quadprog.so
/V4/usr/lib64/R/library/quadprog/libs/quadprog.so
/usr/lib64/R/library/quadprog/libs/quadprog.so
